<?php

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function easy_event_settings_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function easy_event_settings_add_meta_box() {
	add_meta_box(
		'event_settings-event-settings',
		__( 'Event settings', 'event_settings' ),
		'easy_event_settings_html',
		'easy_event',
		'normal',
		'default'
	);
}

add_action( 'add_meta_boxes', 'easy_event_settings_add_meta_box' );

function easy_event_settings_html( $post ) {
	wp_nonce_field( '_event_settings_nonce', 'event_settings_nonce' ); ?>

	<div class="ee-row">
		<div class="ee-col-12">
			<label for="easy_event_description"><?php _e( 'Description', 'event_settings' ); ?></label><br>
			<textarea rows="5" class="ee_input_textarea" name="easy_event_description" id="easy_event_description"><?php echo easy_event_settings_get_meta( 'easy_event_description' ); ?></textarea>
		</div>
	</div>
	<div class="ee-row">
		<div class="ee-col-6">
			<label for="easy_event_date_start"><?php _e( 'Start Date', 'event_settings' ); ?></label><br>
			<input class="ee_input_text ee-input-date" data-format="d/m/Y" type="text" name="easy_event_date_start" id="easy_event_date_start" value="<?php echo easy_event_settings_get_meta( 'easy_event_date_start' ); ?>">
		</div>
		<div class="ee-col-6">
			<label for="easy_event_time_start"><?php _e( 'Start Time', 'event_settings' ); ?></label><br>
			<input class="ee_input_text ee-input-time" data-format="H:i" type="text" name="easy_event_time_start" id="easy_event_time_start" value="<?php echo easy_event_settings_get_meta( 'easy_event_time_start' ); ?>">
		</div>
	</div>

	<div class="ee-row">
		<div class="ee-col-6">
			<label for="easy_event_date_finish"><?php _e( 'Finish Date', 'event_settings' ); ?></label><br>
			<input class="ee_input_text ee-input-date" data-format="d/m/Y" type="text" name="easy_event_date_finish" id="easy_event_date_finish" value="<?php echo easy_event_settings_get_meta( 'easy_event_date_finish' ); ?>">
		</div>
		<div class="ee-col-6">
			<label for="easy_event_time_finish"><?php _e( 'Finish Time', 'event_settings' ); ?></label><br>
			<input class="ee_input_text ee-input-time" data-format="H:i" type="text" name="easy_event_time_finish" id="easy_event_time_finish" value="<?php echo easy_event_settings_get_meta( 'easy_event_time_finish' ); ?>">
		</div>

	</div>

	<div class="ee-row">
		<div class="ee-col-12">
			<label for="easy_event_address"><?php _e( 'Address', 'event_settings' ); ?></label><br>
			<input class="ee_input_text" type="text" name="easy_event_address" id="easy_event_address" value="<?php echo easy_event_settings_get_meta( 'easy_event_address' ); ?>">
		</div>
	</div>
	<div class="ee-row ee-hidden">
		<div class="ee-col-12">
			<label for="easy_event_map"><?php _e( 'Location', 'event_settings' ); ?></label><br>
			<input class="ee_input_text" type="text" name="easy_event_map" id="easy_event_map" value="<?php echo easy_event_settings_get_meta( 'easy_event_map' ); ?>">
		</div>
	</div>
	<?php
}

function easy_event_settings_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
		return;
	}
	if ( ! isset( $_POST['event_settings_nonce'] ) || ! wp_verify_nonce( $_POST['event_settings_nonce'], '_event_settings_nonce' ) ) {
		return;
	}
	if ( ! current_user_can( 'edit_post', $post_id ) ) {
		return;
	}

	if ( isset( $_POST['easy_event_description'] ) ) {
		update_post_meta( $post_id, 'easy_event_description', esc_attr( $_POST['easy_event_description'] ) );
	}
	if ( isset( $_POST['easy_event_date_start'] ) ) {
		update_post_meta( $post_id, 'easy_event_date_start', esc_attr( $_POST['easy_event_date_start'] ) );
	}
	if ( isset( $_POST['easy_event_time_start'] ) ) {
		update_post_meta( $post_id, 'easy_event_time_start', esc_attr( $_POST['easy_event_time_start'] ) );
	}
	if ( isset( $_POST['easy_event_date_finish'] ) ) {
		update_post_meta( $post_id, 'easy_event_date_finish', esc_attr( $_POST['easy_event_date_finish'] ) );
	}
	if ( isset( $_POST['easy_event_time_finish'] ) ) {
		update_post_meta( $post_id, 'easy_event_time_finish', esc_attr( $_POST['easy_event_time_finish'] ) );
	}
	if ( isset( $_POST['easy_event_address'] ) ) {
		update_post_meta( $post_id, 'easy_event_address', esc_attr( $_POST['easy_event_address'] ) );
	}
	if ( isset( $_POST['easy_event_map'] ) ) {
		update_post_meta( $post_id, 'easy_event_map', esc_attr( $_POST['easy_event_map'] ) );
	}
}

add_action( 'save_post', 'easy_event_settings_save' );

/*
	Usage: easy_event_settings_get_meta( 'easy_event_description' )
	Usage: easy_event_settings_get_meta( 'easy_event_date_start' )
	Usage: easy_event_settings_get_meta( 'easy_event_time_start' )
	Usage: easy_event_settings_get_meta( 'easy_event_date_finish' )
	Usage: easy_event_settings_get_meta( 'easy_event_time_finish' )
	Usage: easy_event_settings_get_meta( 'easy_event_address' )
	Usage: easy_event_settings_get_meta( 'easy_event_map' )
*/
